apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
  - NodePort
  ports:
  - port: 90
    targetPort: 90
