apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: NodePort
  ports:
  - port: 90
    targetPort: 90
