apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    -  mountPath: /tmp
       name: pv
  volumes:
  - name: pv
    persistentVolumeClaim:
      claimName: my-disk-claim
